-- ============================================================
-- 11. RBAC
-- PURPOSE: Role-Based Access Control following Project Template
-- ============================================================

-- USE ROLE
USE ROLE ACCOUNTADMIN;

-- USE WAREHOUSE
USE WAREHOUSE HOSPITAL_WH;

-- USE DATABASE
USE DATABASE HOSPITAL_DW;

-- CREATE ROLES
CREATE OR REPLACE ROLE HOSPITAL_ENGINEER_ROLE;

CREATE OR REPLACE ROLE HOSPITAL_ANALYST_ROLE;

CREATE OR REPLACE ROLE HOSPITAL_VIEWER_ROLE;

-- CREATE USERS
CREATE OR REPLACE USER HOSPITAL_ENGINEER_USER
PASSWORD = 'Engineer@123'
DEFAULT_ROLE = HOSPITAL_ENGINEER_ROLE
DEFAULT_WAREHOUSE = HOSPITAL_WH;

CREATE OR REPLACE USER HOSPITAL_ANALYST_USER
PASSWORD = 'Analyst@123'
DEFAULT_ROLE = HOSPITAL_ANALYST_ROLE
DEFAULT_WAREHOUSE = HOSPITAL_WH;

CREATE OR REPLACE USER HOSPITAL_VIEWER_USER
PASSWORD = 'Viewer@123'
DEFAULT_ROLE = HOSPITAL_VIEWER_ROLE
DEFAULT_WAREHOUSE = HOSPITAL_WH;

-- GRANT ROLES TO USERS
GRANT ROLE HOSPITAL_ENGINEER_ROLE TO USER HOSPITAL_ENGINEER_USER;

GRANT ROLE HOSPITAL_ANALYST_ROLE TO USER HOSPITAL_ANALYST_USER;

GRANT ROLE HOSPITAL_VIEWER_ROLE TO USER HOSPITAL_VIEWER_USER;


-- ============================================================
-- ENGINEER ROLE ACCESS
-- ============================================================
GRANT USAGE
ON WAREHOUSE HOSPITAL_WH
TO ROLE HOSPITAL_ENGINEER_ROLE;

GRANT USAGE
ON DATABASE HOSPITAL_DW
TO ROLE HOSPITAL_ENGINEER_ROLE;

GRANT USAGE
ON ALL SCHEMAS IN DATABASE HOSPITAL_DW
TO ROLE HOSPITAL_ENGINEER_ROLE;

GRANT ALL PRIVILEGES
ON ALL TABLES IN SCHEMA HOSPITAL_DW.RAW
TO ROLE HOSPITAL_ENGINEER_ROLE;

GRANT ALL PRIVILEGES
ON ALL TABLES IN SCHEMA HOSPITAL_DW.CORE
TO ROLE HOSPITAL_ENGINEER_ROLE;

GRANT ALL PRIVILEGES
ON ALL DYNAMIC TABLES IN SCHEMA HOSPITAL_DW.MART
TO ROLE HOSPITAL_ENGINEER_ROLE;

GRANT ALL PRIVILEGES
ON ALL VIEWS IN SCHEMA HOSPITAL_DW.MART
TO ROLE HOSPITAL_ENGINEER_ROLE;

GRANT ALL PRIVILEGES
ON ALL MATERIALIZED VIEWS IN SCHEMA HOSPITAL_DW.MART
TO ROLE HOSPITAL_ENGINEER_ROLE;


-- ============================================================
-- ANALYST ROLE ACCESS
-- ============================================================
GRANT USAGE
ON WAREHOUSE HOSPITAL_WH
TO ROLE HOSPITAL_ANALYST_ROLE;

GRANT USAGE
ON DATABASE HOSPITAL_DW
TO ROLE HOSPITAL_ANALYST_ROLE;

GRANT USAGE
ON SCHEMA HOSPITAL_DW.MART
TO ROLE HOSPITAL_ANALYST_ROLE;

GRANT SELECT
ON ALL DYNAMIC TABLES IN SCHEMA HOSPITAL_DW.MART
TO ROLE HOSPITAL_ANALYST_ROLE;

GRANT SELECT
ON ALL VIEWS IN SCHEMA HOSPITAL_DW.MART
TO ROLE HOSPITAL_ANALYST_ROLE;

GRANT SELECT
ON ALL MATERIALIZED VIEWS IN SCHEMA HOSPITAL_DW.MART
TO ROLE HOSPITAL_ANALYST_ROLE;


-- ============================================================
-- VIEWER ROLE ACCESS
-- ============================================================
GRANT USAGE
ON WAREHOUSE HOSPITAL_WH
TO ROLE HOSPITAL_VIEWER_ROLE;

GRANT USAGE
ON DATABASE HOSPITAL_DW
TO ROLE HOSPITAL_VIEWER_ROLE;

GRANT USAGE
ON SCHEMA HOSPITAL_DW.MART
TO ROLE HOSPITAL_VIEWER_ROLE;

-- VIEWER DYNAMIC TABLE ACCESS
GRANT SELECT
ON ALL DYNAMIC TABLES IN SCHEMA HOSPITAL_DW.MART
TO ROLE HOSPITAL_VIEWER_ROLE;

-- VIEWER VIEW ACCESS
GRANT SELECT
ON ALL VIEWS IN SCHEMA HOSPITAL_DW.MART
TO ROLE HOSPITAL_VIEWER_ROLE;

-- VIEWER MATERIALIZED VIEW ACCESS
GRANT SELECT
ON ALL MATERIALIZED VIEWS IN SCHEMA HOSPITAL_DW.MART
TO ROLE HOSPITAL_VIEWER_ROLE;


-- ============================================================
-- FUTURE ACCESS (FOR VIEWER)
-- ============================================================
GRANT SELECT
ON FUTURE DYNAMIC TABLES IN SCHEMA HOSPITAL_DW.MART
TO ROLE HOSPITAL_VIEWER_ROLE;

GRANT SELECT
ON FUTURE VIEWS IN SCHEMA HOSPITAL_DW.MART
TO ROLE HOSPITAL_VIEWER_ROLE;

GRANT SELECT
ON FUTURE MATERIALIZED VIEWS IN SCHEMA HOSPITAL_DW.MART
TO ROLE HOSPITAL_VIEWER_ROLE;


-- ============================================================
-- VERIFICATION
-- ============================================================
SHOW ROLES;
SHOW USERS;

SHOW GRANTS TO ROLE HOSPITAL_ENGINEER_ROLE;
SHOW GRANTS TO ROLE HOSPITAL_ANALYST_ROLE;
SHOW GRANTS TO ROLE HOSPITAL_VIEWER_ROLE;
