-- ============================================================
-- 12. MASKING POLICY
-- PURPOSE: Dynamic Data Masking for sensitive columns (PII)
-- ============================================================

USE ROLE SYSADMIN;
USE DATABASE HOSPITAL_DW;
USE SCHEMA GOVERNANCE;

-- =========================
-- UNSET EXISTING POLICIES (To prevent compilation errors)
-- =========================
ALTER TABLE IF EXISTS HOSPITAL_DW.CORE.CORE_PATIENTS MODIFY COLUMN PHONE UNSET MASKING POLICY;
ALTER TABLE IF EXISTS HOSPITAL_DW.CORE.CORE_PATIENTS MODIFY COLUMN EMAIL UNSET MASKING POLICY;
ALTER TABLE IF EXISTS HOSPITAL_DW.CORE.CORE_PATIENTS MODIFY COLUMN FULL_NAME UNSET MASKING POLICY;

ALTER DYNAMIC TABLE IF EXISTS HOSPITAL_DW.MART.DIM_PATIENT MODIFY COLUMN PHONE UNSET MASKING POLICY;
ALTER DYNAMIC TABLE IF EXISTS HOSPITAL_DW.MART.DIM_PATIENT MODIFY COLUMN EMAIL UNSET MASKING POLICY;
ALTER DYNAMIC TABLE IF EXISTS HOSPITAL_DW.MART.DIM_PATIENT MODIFY COLUMN FULL_NAME UNSET MASKING POLICY;

-- =========================
-- CREATE POLICIES
-- =========================

-- PHONE MASKING
CREATE OR REPLACE MASKING POLICY HOSPITAL_DW.GOVERNANCE.MASK_PHONE AS
    (VAL VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN ('HOSPITAL_ENGINEER_ROLE', 'HOSPITAL_ANALYST_ROLE', 'HOSPITAL_VIEWER_ROLE', 'ACCOUNTADMIN') THEN VAL
        WHEN VAL IS NULL THEN NULL
        ELSE CONCAT('******', RIGHT(VAL, 4))
    END;

-- EMAIL MASKING
CREATE OR REPLACE MASKING POLICY HOSPITAL_DW.GOVERNANCE.MASK_EMAIL AS
    (VAL VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN ('HOSPITAL_ENGINEER_ROLE', 'HOSPITAL_ANALYST_ROLE', 'HOSPITAL_VIEWER_ROLE', 'ACCOUNTADMIN') THEN VAL
        WHEN VAL IS NULL THEN NULL
        WHEN CHARINDEX('@', VAL) > 0 THEN CONCAT('****', SUBSTR(VAL, CHARINDEX('@', VAL)))
        ELSE '****'
    END;

-- NAME MASKING
CREATE OR REPLACE MASKING POLICY HOSPITAL_DW.GOVERNANCE.MASK_PATIENT_NAME AS
    (VAL VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN ('HOSPITAL_ENGINEER_ROLE', 'HOSPITAL_ANALYST_ROLE', 'HOSPITAL_VIEWER_ROLE', 'ACCOUNTADMIN') THEN VAL
        ELSE '****'
    END;

-- =========================
-- APPLY POLICIES (CORE)
-- =========================
ALTER TABLE HOSPITAL_DW.CORE.CORE_PATIENTS MODIFY COLUMN PHONE SET MASKING POLICY HOSPITAL_DW.GOVERNANCE.MASK_PHONE;
ALTER TABLE HOSPITAL_DW.CORE.CORE_PATIENTS MODIFY COLUMN EMAIL SET MASKING POLICY HOSPITAL_DW.GOVERNANCE.MASK_EMAIL;
ALTER TABLE HOSPITAL_DW.CORE.CORE_PATIENTS MODIFY COLUMN FULL_NAME SET MASKING POLICY HOSPITAL_DW.GOVERNANCE.MASK_PATIENT_NAME;

-- =========================
-- APPLY POLICIES (MART)
-- =========================
ALTER DYNAMIC TABLE HOSPITAL_DW.MART.DIM_PATIENT MODIFY COLUMN PHONE SET MASKING POLICY HOSPITAL_DW.GOVERNANCE.MASK_PHONE;
ALTER DYNAMIC TABLE HOSPITAL_DW.MART.DIM_PATIENT MODIFY COLUMN EMAIL SET MASKING POLICY HOSPITAL_DW.GOVERNANCE.MASK_EMAIL;
ALTER DYNAMIC TABLE HOSPITAL_DW.MART.DIM_PATIENT MODIFY COLUMN FULL_NAME SET MASKING POLICY HOSPITAL_DW.GOVERNANCE.MASK_PATIENT_NAME;
