-- ============================================================
-- 13. VALIDATION QUERY
-- PURPOSE: Check data quality across layers
-- ============================================================

USE DATABASE HOSPITAL_DW;
USE WAREHOUSE HOSPITAL_WH;

-- ----------------------------------------------------------
-- 1. ROW COUNTS (RAW vs CORE)
-- ----------------------------------------------------------
SELECT
    'PATIENTS' AS DOMAIN,
    (SELECT COUNT(*) FROM HOSPITAL_DW.RAW.RAW_PATIENTS) AS RAW_COUNT,
    (SELECT COUNT(*) FROM HOSPITAL_DW.CORE.CORE_PATIENTS) AS CORE_COUNT,
    ROUND((SELECT COUNT(*) FROM HOSPITAL_DW.CORE.CORE_PATIENTS) * 100.0 / NULLIF((SELECT COUNT(*) FROM HOSPITAL_DW.RAW.RAW_PATIENTS), 0), 1) AS PASS_RATE_PCT
UNION ALL
SELECT
    'APPOINTMENTS',
    (SELECT COUNT(*) FROM HOSPITAL_DW.RAW.RAW_APPOINTMENTS),
    (SELECT COUNT(*) FROM HOSPITAL_DW.CORE.CORE_APPOINTMENTS),
    ROUND((SELECT COUNT(*) FROM HOSPITAL_DW.CORE.CORE_APPOINTMENTS) * 100.0 / NULLIF((SELECT COUNT(*) FROM HOSPITAL_DW.RAW.RAW_APPOINTMENTS), 0), 1)
UNION ALL
SELECT
    'BILLING',
    (SELECT COUNT(*) FROM HOSPITAL_DW.RAW.RAW_BILLING),
    (SELECT COUNT(*) FROM HOSPITAL_DW.CORE.CORE_BILLING),
    ROUND((SELECT COUNT(*) FROM HOSPITAL_DW.CORE.CORE_BILLING) * 100.0 / NULLIF((SELECT COUNT(*) FROM HOSPITAL_DW.RAW.RAW_BILLING), 0), 1);

-- ----------------------------------------------------------
-- 2. REJECTED RECORDS ANALYSIS
-- ----------------------------------------------------------
SELECT
    SOURCE_TABLE,
    REJECTION_REASON,
    COUNT(*) AS REJECTED_COUNT
FROM HOSPITAL_DW.RAW.RAW_EXCEPTIONS
GROUP BY SOURCE_TABLE, REJECTION_REASON
ORDER BY REJECTED_COUNT DESC;

-- ----------------------------------------------------------
-- 3. DIMENSION DUPLICATE CHECK
-- ----------------------------------------------------------
SELECT 'DIM_PATIENT' AS TBL, PATIENT_KEY, COUNT(*) AS CNT
FROM HOSPITAL_DW.MART.DIM_PATIENT GROUP BY 1,2 HAVING CNT > 1
UNION ALL
SELECT 'DIM_DOCTOR', DOCTOR_KEY, COUNT(*)
FROM HOSPITAL_DW.MART.DIM_DOCTOR GROUP BY 1,2 HAVING CNT > 1;

-- ----------------------------------------------------------
-- 4. NULL FOREIGN KEY CHECK
-- ----------------------------------------------------------
SELECT 'FACT_APPOINTMENT' AS FACT_TABLE, 'NULL_PATIENT_FK' AS ISSUE, COUNT(*) AS CNT
FROM HOSPITAL_DW.MART.FACT_APPOINTMENT WHERE PATIENT_KEY IS NULL
UNION ALL
SELECT 'FACT_BILLING', 'NULL_PATIENT_FK', COUNT(*)
FROM HOSPITAL_DW.MART.FACT_BILLING WHERE PATIENT_KEY IS NULL;

-- ----------------------------------------------------------
-- 5. BUSINESS RULES CHECK
-- ----------------------------------------------------------
-- Should be 0
SELECT COUNT(*) AS NEGATIVE_AMOUNTS
FROM HOSPITAL_DW.CORE.CORE_BILLING
WHERE GROSS_AMOUNT < 0 OR NET_AMOUNT < 0;
