-- ============================================================
-- 14. JOIN QUERY
-- PURPOSE: Analytical views with multiple JOINs
-- ============================================================

USE DATABASE HOSPITAL_DW;
USE SCHEMA MART;
USE WAREHOUSE HOSPITAL_WH;

-- ----------------------------------------------------------
-- VIEW: PATIENT UTILIZATION
-- ----------------------------------------------------------
CREATE OR REPLACE SECURE VIEW HOSPITAL_DW.MART.VW_PATIENT_UTILIZATION AS
SELECT
    p.PATIENT_KEY,
    p.PATIENT_ID,
    p.FULL_NAME,
    p.AGE_GROUP,
    COALESCE(appt.TOTAL_APPOINTMENTS, 0) AS TOTAL_APPOINTMENTS,
    COALESCE(appt.COMPLETED_VISITS, 0) AS COMPLETED_VISITS,
    COALESCE(bill.TOTAL_BILLS, 0) AS TOTAL_BILLS,
    COALESCE(bill.LIFETIME_NET_REVENUE, 0) AS LIFETIME_NET_REVENUE,
    appt.LAST_VISIT_DATE
FROM HOSPITAL_DW.MART.DIM_PATIENT p
LEFT JOIN (
    SELECT
        PATIENT_KEY,
        COUNT(*) AS TOTAL_APPOINTMENTS,
        SUM(IS_COMPLETED) AS COMPLETED_VISITS,
        MAX(APPT_DATE) AS LAST_VISIT_DATE
    FROM HOSPITAL_DW.MART.FACT_APPOINTMENT
    GROUP BY PATIENT_KEY
) appt ON p.PATIENT_KEY = appt.PATIENT_KEY
LEFT JOIN (
    SELECT
        PATIENT_KEY,
        COUNT(*) AS TOTAL_BILLS,
        SUM(NET_AMOUNT) AS LIFETIME_NET_REVENUE
    FROM HOSPITAL_DW.MART.FACT_BILLING
    GROUP BY PATIENT_KEY
) bill ON p.PATIENT_KEY = bill.PATIENT_KEY;

-- ----------------------------------------------------------
-- VIEW: DAILY OPD TREND
-- ----------------------------------------------------------
CREATE OR REPLACE SECURE VIEW HOSPITAL_DW.MART.VW_DAILY_OPD_TREND AS
SELECT
    fa.APPT_DATE,
    dd.DAY_NAME,
    dd.IS_WEEKEND,
    dd.YEAR_MONTH,
    COUNT(*) AS TOTAL_APPOINTMENTS,
    SUM(fa.IS_COMPLETED) AS COMPLETED_VISITS,
    SUM(fa.IS_NO_SHOW) AS NO_SHOWS,
    COUNT(DISTINCT fa.DOCTOR_KEY) AS UNIQUE_DOCTORS,
    ROUND(COUNT(*) * 1.0 / NULLIF(COUNT(DISTINCT fa.DOCTOR_KEY), 0), 2) AS AVG_APPT_PER_DOCTOR
FROM HOSPITAL_DW.MART.FACT_APPOINTMENT fa
INNER JOIN HOSPITAL_DW.MART.DIM_DATE dd ON fa.DATE_KEY = dd.DATE_KEY
GROUP BY fa.APPT_DATE, dd.DAY_NAME, dd.IS_WEEKEND, dd.YEAR_MONTH;

-- ----------------------------------------------------------
-- VIEW: DOCTOR PERFORMANCE
-- ----------------------------------------------------------
CREATE OR REPLACE SECURE VIEW HOSPITAL_DW.MART.VW_DOCTOR_PERFORMANCE AS
SELECT
    d.DOCTOR_NAME,
    d.PRIMARY_DEPARTMENT,
    COUNT(*) AS TOTAL_APPOINTMENTS,
    SUM(fa.IS_COMPLETED) AS COMPLETED,
    SUM(fa.IS_NO_SHOW) AS NO_SHOWS,
    COUNT(DISTINCT fa.PATIENT_KEY) AS UNIQUE_PATIENTS
FROM HOSPITAL_DW.MART.FACT_APPOINTMENT fa
INNER JOIN HOSPITAL_DW.MART.DIM_DOCTOR d ON fa.DOCTOR_KEY = d.DOCTOR_KEY
GROUP BY d.DOCTOR_NAME, d.PRIMARY_DEPARTMENT;

-- GRANT ACCESS
GRANT SELECT ON ALL VIEWS IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_BUSINESS_USER;
