-- ============================================================
-- 17. SECURE VIEWS
-- PURPOSE: 6 Analytical Secure Views for Business Users
-- ============================================================

USE DATABASE HOSPITAL_DW;
USE SCHEMA MART;

-- 1. VW_REVENUE_BY_DEPARTMENT
-- Calculates total revenue and average bill amount per department
CREATE OR REPLACE SECURE VIEW VW_REVENUE_BY_DEPARTMENT AS
SELECT 
    DEPARTMENT,
    COUNT(BILL_ID) AS TOTAL_BILLS,
    SUM(NET_AMOUNT) AS TOTAL_REVENUE,
    ROUND(AVG(NET_AMOUNT), 2) AS AVG_BILL_AMOUNT
FROM HOSPITAL_DW.MART.FACT_BILLING
GROUP BY DEPARTMENT;

-- 2. VW_NO_SHOW_ANALYSIS
-- Analyzes the no-show rate per doctor using the pre-calculated IS_NO_SHOW flag!
CREATE OR REPLACE SECURE VIEW VW_NO_SHOW_ANALYSIS AS
SELECT 
    DOCTOR_NAME,
    DEPARTMENT,
    COUNT(APPT_ID) AS TOTAL_APPOINTMENTS,
    SUM(IS_NO_SHOW) AS NO_SHOW_COUNT,
    ROUND(SUM(IS_NO_SHOW) * 100.0 / NULLIF(COUNT(APPT_ID), 0), 2) AS NO_SHOW_PERCENTAGE
FROM HOSPITAL_DW.MART.FACT_APPOINTMENT
GROUP BY DOCTOR_NAME, DEPARTMENT;

-- 3. VW_PATIENT_DEMOGRAPHICS
-- Aggregates patient demographics for marketing/analysis
CREATE OR REPLACE SECURE VIEW VW_PATIENT_DEMOGRAPHICS AS
SELECT 
    GENDER,
    CITY,
    STATE,
    COUNT(PATIENT_ID) AS TOTAL_PATIENTS
FROM HOSPITAL_DW.MART.DIM_PATIENT
GROUP BY GENDER, CITY, STATE;

-- 4. VW_TOP_INSURERS
-- Identifies the most common insurance providers using the IS_INSURANCE flag!
CREATE OR REPLACE SECURE VIEW VW_TOP_INSURERS AS
SELECT 
    INSURER_NAME,
    COUNT(BILL_ID) AS BILL_COUNT,
    SUM(NET_AMOUNT) AS TOTAL_INSURANCE_BILLED
FROM HOSPITAL_DW.MART.FACT_BILLING
WHERE IS_INSURANCE = 1
  AND INSURER_NAME IS NOT NULL
GROUP BY INSURER_NAME
ORDER BY TOTAL_INSURANCE_BILLED DESC;

-- 5. VW_DAILY_CLINIC_ROSTER
-- A clean view of all scheduled and completed appointments
CREATE OR REPLACE SECURE VIEW VW_DAILY_CLINIC_ROSTER AS
SELECT 
    a.APPT_DATE,
    a.SLOT,
    p.FULL_NAME AS PATIENT_NAME,
    a.DOCTOR_NAME,
    a.DEPARTMENT,
    a.STATUS
FROM HOSPITAL_DW.MART.FACT_APPOINTMENT a
INNER JOIN HOSPITAL_DW.MART.DIM_PATIENT p
    ON a.PATIENT_KEY = p.PATIENT_KEY
WHERE (a.IS_SCHEDULED = 1 OR a.IS_COMPLETED = 1);

-- 6. VW_HIGH_VALUE_PATIENTS
-- Identifies VIP/High-Value patients who have spent the most at the hospital
CREATE OR REPLACE SECURE VIEW VW_HIGH_VALUE_PATIENTS AS
SELECT 
    p.PATIENT_ID,
    p.FULL_NAME,
    p.PHONE,
    p.EMAIL,
    COUNT(b.BILL_ID) AS TOTAL_VISITS,
    SUM(b.NET_AMOUNT) AS LIFETIME_VALUE
FROM HOSPITAL_DW.MART.FACT_BILLING b
INNER JOIN HOSPITAL_DW.MART.DIM_PATIENT p 
    ON b.PATIENT_KEY = p.PATIENT_KEY
GROUP BY p.PATIENT_ID, p.FULL_NAME, p.PHONE, p.EMAIL
ORDER BY LIFETIME_VALUE DESC;

-- ============================================================
-- GRANT PRIVILEGES TO ANALYST AND MANAGER
-- ============================================================
GRANT SELECT ON VIEW HOSPITAL_DW.MART.VW_REVENUE_BY_DEPARTMENT TO ROLE HOSPITAL_ANALYST;
GRANT SELECT ON VIEW HOSPITAL_DW.MART.VW_NO_SHOW_ANALYSIS TO ROLE HOSPITAL_ANALYST;
GRANT SELECT ON VIEW HOSPITAL_DW.MART.VW_PATIENT_DEMOGRAPHICS TO ROLE HOSPITAL_ANALYST;
GRANT SELECT ON VIEW HOSPITAL_DW.MART.VW_TOP_INSURERS TO ROLE HOSPITAL_ANALYST;
GRANT SELECT ON VIEW HOSPITAL_DW.MART.VW_DAILY_CLINIC_ROSTER TO ROLE HOSPITAL_ANALYST;
GRANT SELECT ON VIEW HOSPITAL_DW.MART.VW_HIGH_VALUE_PATIENTS TO ROLE HOSPITAL_ANALYST;

GRANT SELECT ON VIEW HOSPITAL_DW.MART.VW_REVENUE_BY_DEPARTMENT TO ROLE HOSPITAL_MANAGER;
GRANT SELECT ON VIEW HOSPITAL_DW.MART.VW_NO_SHOW_ANALYSIS TO ROLE HOSPITAL_MANAGER;
GRANT SELECT ON VIEW HOSPITAL_DW.MART.VW_PATIENT_DEMOGRAPHICS TO ROLE HOSPITAL_MANAGER;
GRANT SELECT ON VIEW HOSPITAL_DW.MART.VW_TOP_INSURERS TO ROLE HOSPITAL_MANAGER;
GRANT SELECT ON VIEW HOSPITAL_DW.MART.VW_DAILY_CLINIC_ROSTER TO ROLE HOSPITAL_MANAGER;
GRANT SELECT ON VIEW HOSPITAL_DW.MART.VW_HIGH_VALUE_PATIENTS TO ROLE HOSPITAL_MANAGER;
